spring:
  datasource:
    url: jdbc:mysql://users.c6dbmianpmse.us-east-1.rds.amazonaws.com/users
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
appDescription: "Users microservice"
appVersion: "1.0.0"

